### ISSUE TITLE
Inconsistent results with nnformer on the ACDC dataset

### ISSUE THREAD

**Issue by Cuthbert-Huang** [Amshaker/unetr_plus_plus#1]
Hello, thank you for your excellent work. But I have a doubt that your work is not consistent with the results of nnformer on the ACDC dataset. I would like to know the reason if possible.

**Comment by mmaaz60** [comment]
> Hello, thank you for your excellent work. But I have a doubt that your work is not consistent with the results of nnformer on the ACDC dataset. I would like to know the reason if possible.

Hi @Cuthbert-Huang,

Thank You for your interest in our work. For ACDC, we report our reproduced results for nnFormer using their official codebase and configuration. Please let me know if it answers your question.

Thanks

**Comment by Amshaker** [comment]
Hi @Cuthbert-Huang ,
Thank you for your interest in our work. The DSC of nnFormer is reproduced by us based on their codebase using a single model (without ensembling) and without any pre-training. Please let us know if have other questions.

Thank you,
Abdelrahman.

**Comment by Cuthbert-Huang** [comment]
I understand, thanks
