### ISSUE TITLE
How can i train model in unetr++ with my own dataset?

### ISSUE THREAD

**Issue by Overflowu7** [Amshaker/unetr_plus_plus#10]
Hi! Your Idea is owesome ! And I'm interesting in how can i do in order to adjust with my own dataset. I have generated corresponding json file ,but I still don't know what I should do next.Should I create a new trainer file? or do something else?

**Comment by Amshaker** [comment]
Hi @Overflowu7 ,

Thank you for your interest in our work.

To train UNETR++ for a new dataset, you have to do the appropriate data pre-processing first. It depends on each dataset. After that, you can use, for example, the model architecture of ACDC and create new trainings files In _unetr_plus_plus/tree/main/unetr_pp/training/network_training_. It is similar to [Trainer_acdc.py](https://github.com/Amshaker/unetr_plus_plus/blob/main/unetr_pp/training/network_training/Trainer_acdc.py), [network_trainer_acdc.py](https://github.com/Amshaker/unetr_plus_plus/blob/main/unetr_pp/training/network_training/network_trainer_acdc.py), and [unetr_pp_trainer_acdc.py](https://github.com/Amshaker/unetr_plus_plus/blob/main/unetr_pp/training/network_training/unetr_pp_trainer_acdc.py). Please note that the folder structure of the data should follow the same structure as in [run_training_acdc.sh](https://github.com/Amshaker/unetr_plus_plus/blob/main/run_training_acdc.sh)

I hope my answer helps you to do that.

Best regards,
Abdelrahman.

**Comment by Overflowu7** [comment]
Thank you for your prompt reply! Based on your answer, I have another two questions.   
1.I found that unetr_pp_trainer_synapse.py  import UNETR_PP from unetr_pp.network_architecture.synapse.unetr_pp_synapse, should I make a new file in network_architecture which is similar to synapse and acdc?
2.I found that the batch size and crop size should be adjust in the file default_configuration.py , and I also want to know if there are other files that need to be adjusted?

**Comment by Amshaker** [comment]
1) Yes, you have to create similar file for your dataset. Please take care that you may need to change the architecture slightly according to the size of your input data. For example, Synapse the down-sampling layers are designed for input 63x128x128. For ACDC, the down-sampling has different kernels because the input size is different.

2) If this is a new dataset, you just have to change in there. If you need to change it for the current datasets, you have to change the .pkl file for that.

**Comment by 975827738** [comment]
> 2\. 如果需要更改当前数据集的 .pkl 文件



> Hi @Overflowu7 ,
> 
> Thank you for your interest in our work.
> 
> To train UNETR++ for a new dataset, you have to do the appropriate data pre-processing first. It depends on each dataset. You can follow setting-up dataset section here for pre-processing: https://github.com/282857341/nnFormer#2-setting-up-the-datasets. After that, you can use, for example, the model architecture of ACDC and create new trainings files In _unetr_plus_plus/tree/main/unetr_pp/training/network_training_. It is similar to [Trainer_acdc.py](https://github.com/Amshaker/unetr_plus_plus/blob/main/unetr_pp/training/network_training/Trainer_acdc.py), [network_trainer_acdc.py](https://github.com/Amshaker/unetr_plus_plus/blob/main/unetr_pp/training/network_training/network_trainer_acdc.py), and [unetr_pp_trainer_acdc.py](https://github.com/Amshaker/unetr_plus_plus/blob/main/unetr_pp/training/network_training/unetr_pp_trainer_acdc.py). Please note that the folder structure of the data should follow the same structure as in [run_training_acdc.sh](https://github.com/Amshaker/unetr_plus_plus/blob/main/run_training_acdc.sh)
> 
> I hope my answer helps you to do that.
> 
> Best regards, Abdelrahman.

Hello, may I ask how to obtain the pkl file

**Comment by 975827738** [comment]
> 2\. 如果需要更改当前数据集的 .pkl 文件



> Hi @Overflowu7 ,
> 
> Thank you for your interest in our work.
> 
> To train UNETR++ for a new dataset, you have to do the appropriate data pre-processing first. It depends on each dataset. You can follow setting-up dataset section here for pre-processing: https://github.com/282857341/nnFormer#2-setting-up-the-datasets. After that, you can use, for example, the model architecture of ACDC and create new trainings files In _unetr_plus_plus/tree/main/unetr_pp/training/network_training_. It is similar to [Trainer_acdc.py](https://github.com/Amshaker/unetr_plus_plus/blob/main/unetr_pp/training/network_training/Trainer_acdc.py), [network_trainer_acdc.py](https://github.com/Amshaker/unetr_plus_plus/blob/main/unetr_pp/training/network_training/network_trainer_acdc.py), and [unetr_pp_trainer_acdc.py](https://github.com/Amshaker/unetr_plus_plus/blob/main/unetr_pp/training/network_training/unetr_pp_trainer_acdc.py). Please note that the folder structure of the data should follow the same structure as in [run_training_acdc.sh](https://github.com/Amshaker/unetr_plus_plus/blob/main/run_training_acdc.sh)
> 
> I hope my answer helps you to do that.
> 
> Best regards, Abdelrahman.

Hello, may I ask how to obtain the pkl file

**Comment by 975827738** [comment]
> Hi! Your Idea is owesome ! And I'm interesting in how can i do in order to adjust with my own dataset. I have generated corresponding json file ,but I still don't know what I should do next.Should I create a new trainer file? or do something else?

Hello, may I ask how to obtain the pkl file

**Comment by Overflowu7** [comment]
Just change the corresponding path to the one you need.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Amshaker/unetr_plus_plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月17日(星期三) 下午4:14
***@***.***&gt;;
抄送:&nbsp;"-           ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Amshaker/unetr_plus_plus] How can i train model in unetr++ with my own dataset? (Issue #10)





  
Hi! Your Idea is owesome ! And I'm interesting in how can i do in order to adjust with my own dataset. I have generated corresponding json file ,but I still don't know what I should do next.Should I create a new trainer file? or do something else?
  
Hello, may I ask how to obtain the pkl file

**Comment by 975827738** [comment]
> Just change the corresponding path to the one you need.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Amshaker/unetr_plus_plus" ***@***.***&gt;; 发送时间:&nbsp;2024年4月17日(星期三) 下午4:14 ***@***.***&gt;; 抄送:&nbsp;"- ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Amshaker/unetr_plus_plus] How can i train model in unetr++ with my own dataset? (Issue #10) Hi! Your Idea is owesome ! And I'm interesting in how can i do in order to adjust with my own dataset. I have generated corresponding json file ,but I still don't know what I should do next.Should I create a new trainer file? or do something else? Hello, may I ask how to obtain the pkl file — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Thank you, could you be more specific? 1. Is this .pkl file automatically generated? 2. In which file should I change thecorresponding path

**Comment by Overflowu7** [comment]
Yes, .pkl files were automatically generated in nnunetv1, but were removed in nnunetv2, now json files are used instead of pkl files! If you still use nnunetv1 ,after each dataset has been processed, you can find the corresponding path of pkl in nnUNet_processed folder like "/nnUNet/nnUNet_processed/Task11_CTPelvic1K/nnUNetPlans_plans_3D.pkl'".






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Amshaker/unetr_plus_plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 下午2:09
***@***.***&gt;;
抄送:&nbsp;"-           ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Amshaker/unetr_plus_plus] How can i train model in unetr++ with my own dataset? (Issue #10)





  
Just change the corresponding path to the one you need.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Amshaker/unetr_plus_plus" @.&gt;; 发送时间:&nbsp;2024年4月17日(星期三) 下午4:14 @.&gt;; 抄送:&nbsp;"- @.@.&gt;; 主题:&nbsp;Re: [Amshaker/unetr_plus_plus] How can i train model in unetr++ with my own dataset? (Issue #10) Hi! Your Idea is owesome ! And I'm interesting in how can i do in order to adjust with my own dataset. I have generated corresponding json file ,but I still don't know what I should do next.Should I create a new trainer file? or do something else? Hello, may I ask how to obtain the pkl file — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
Thank you, could you be more specific? 1. Is this .pkl file automatically generated? 2. In which file should I change thecorresponding path

**Comment by 975827738** [comment]
> Yes, .pkl files were automatically generated in nnunetv1, but were removed in nnunetv2, now json files are used instead of pkl files! If you still use nnunetv1 ,after each dataset has been processed, you can find the corresponding path of pkl in nnUNet_processed folder like "/nnUNet/nnUNet_processed/Task11_CTPelvic1K/nnUNetPlans_plans_3D.pkl'".
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Amshaker/unetr_plus_plus" ***@***.***&gt;; 发送时间:&nbsp;2024年4月18日(星期四) 下午2:09 ***@***.***&gt;; 抄送:&nbsp;"- ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Amshaker/unetr_plus_plus] How can i train model in unetr++ with my own dataset? (Issue #10) Just change the corresponding path to the one you need. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Amshaker/unetr_plus_plus" @.&gt;; 发送时间:&nbsp;2024年4月17日(星期三) 下午4:14 @.&gt;; 抄送:&nbsp;"- @.@.&gt;; 主题:&nbsp;Re: [Amshaker/unetr_plus_plus] How can i train model in unetr++ with my own dataset? (Issue #10) Hi! Your Idea is owesome ! And I'm interesting in how can i do in order to adjust with my own dataset. I have generated corresponding json file ,but I still don't know what I should do next.Should I create a new trainer file? or do something else? Hello, may I ask how to obtain the pkl file — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt; Thank you, could you be more specific? 1. Is this .pkl file automatically generated? 2. In which file should I change thecorresponding path — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Thank you, I understand. Does it mean using Json files instead of pkl files? In this paper, I have generated the Json file for my own dataset, but it shows that there is no pkl file. I found that the pkl file was called in the code. How did you handle it?

**Comment by Overflowu7** [comment]
I haven't run unter++ code since the nnunetv2 update, so I can't provide any more information. I remember that the v1 version will automatically generate the pkl file, and unter++ is based on the v1 version, so I don't know why there is no when your data is generated. I suggest you try to apply the network part of unter++ to nnunetv2 with slight changes.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Amshaker/unetr_plus_plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月18日(星期四) 下午4:59
***@***.***&gt;;
抄送:&nbsp;"-           ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Amshaker/unetr_plus_plus] How can i train model in unetr++ with my own dataset? (Issue #10)





  
Yes, .pkl files were automatically generated in nnunetv1, but were removed in nnunetv2, now json files are used instead of pkl files! If you still use nnunetv1 ,after each dataset has been processed, you can find the corresponding path of pkl in nnUNet_processed folder like "/nnUNet/nnUNet_processed/Task11_CTPelvic1K/nnUNetPlans_plans_3D.pkl'".
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Amshaker/unetr_plus_plus" @.&gt;; 发送时间:&nbsp;2024年4月18日(星期四) 下午2:09 @.&gt;; 抄送:&nbsp;"- @.@.&gt;; 主题:&nbsp;Re: [Amshaker/unetr_plus_plus] How can i train model in unetr++ with my own dataset? (Issue #10) Just change the corresponding path to the one you need. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Amshaker/unetr_plus_plus" @.&gt;; 发送时间:&nbsp;2024年4月17日(星期三) 下午4:14 @.&gt;; 抄送:&nbsp;"- @.@.&gt;; 主题:&nbsp;Re: [Amshaker/unetr_plus_plus] How can i train model in unetr++ with my own dataset? (Issue #10) Hi! Your Idea is owesome ! And I'm interesting in how can i do in order to adjust with my own dataset. I have generated corresponding json file ,but I still don't know what I should do next.Should I create a new trainer file? or do something else? Hello, may I ask how to obtain the pkl file — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt; Thank you, could you be more specific? 1. Is this .pkl file automatically generated? 2. In which file should I change thecorresponding path — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt;
  
Thank you, I understand. Does it mean using Json files instead of pkl files? In this paper, I have generated the Json file for my own dataset, but it shows that there is no pkl file. I found that the pkl file was called in the code. How did you handle it?

**Comment by 975827738** [comment]
> I haven't run unter++ code since the nnunetv2 update, so I can't provide any more information. I remember that the v1 version will automatically generate the pkl file, and unter++ is based on the v1 version, so I don't know why there is no when your data is generated. I suggest you try to apply the network part of unter++ to nnunetv2 with slight changes.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Amshaker/unetr_plus_plus" ***@***.***&gt;; 发送时间:&nbsp;2024年4月18日(星期四) 下午4:59 ***@***.***&gt;; 抄送:&nbsp;"- ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Amshaker/unetr_plus_plus] How can i train model in unetr++ with my own dataset? (Issue #10) Yes, .pkl files were automatically generated in nnunetv1, but were removed in nnunetv2, now json files are used instead of pkl files! If you still use nnunetv1 ,after each dataset has been processed, you can find the corresponding path of pkl in nnUNet_processed folder like "/nnUNet/nnUNet_processed/Task11_CTPelvic1K/nnUNetPlans_plans_3D.pkl'". … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Amshaker/unetr_plus_plus" @.&gt;; 发送时间:&nbsp;2024年4月18日(星期四) 下午2:09 @.&gt;; 抄送:&nbsp;"- @.@.&gt;; 主题:&nbsp;Re: [Amshaker/unetr_plus_plus] How can i train model in unetr++ with my own dataset? (Issue #10) Just change the corresponding path to the one you need. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Amshaker/unetr_plus_plus" @.&gt;; 发送时间:&nbsp;2024年4月17日(星期三) 下午4:14 @.&gt;; 抄送:&nbsp;"- @.@.&gt;; 主题:&nbsp;Re: [Amshaker/unetr_plus_plus] How can i train model in unetr++ with my own dataset? (Issue #10) Hi! Your Idea is owesome ! And I'm interesting in how can i do in order to adjust with my own dataset. I have generated corresponding json file ,but I still don't know what I should do next.Should I create a new trainer file? or do something else? Hello, may I ask how to obtain the pkl file — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt; Thank you, could you be more specific? 1. Is this .pkl file automatically generated? 2. In which file should I change thecorresponding path — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt; Thank you, I understand. Does it mean using Json files instead of pkl files? In this paper, I have generated the Json file for my own dataset, but it shows that there is no pkl file. I found that the pkl file was called in the code. How did you handle it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Ok, thanks for your reply
