### ISSUE TITLE
No module named 'unetr_pp'

### ISSUE THREAD

**Issue by MOMOANNIE** [Amshaker/unetr_plus_plus#12]
Hello, when I run the script run_training.py, this happens, what is going on? path is ok
![image](https://user-images.githubusercontent.com/26375536/223343817-4575abd0-ff27-49aa-8b31-aaf483d83ae0.png)

**Comment by Amshaker** [comment]
Hello,

You have to run it from the main directory path of the repository:

Similar to this command: python unetr_pp/run/run_training.py 3d_fullres unetr_pp_trainer_synapse 2 0

**Comment by MOMOANNIE** [comment]
> Hello,
> 
> You have to run it from the main directory path of the repository:
> 
> Similar to this command: python unetr_pp/run/run_training.py 3d_fullres unetr_pp_trainer_synapse 2 0

I run it from the main directory, and it still reports an error. I try these two commands, but they don’t work.
` python unetr_plus_plus/unetr_pp/run/run_training.py`，` python unetr_pp/run/run_training.py `

The error  as follows:
![image](https://user-images.githubusercontent.com/26375536/224591125-4a7175a9-b2bf-444f-98d8-339ab15b45d8.png)

![image](https://user-images.githubusercontent.com/26375536/224591153-a16dfb31-9187-49d7-98af-f06e94a9e3cc.png)

**Comment by Amshaker** [comment]
Hi @MOMOANNIE,

Please make sure to run the training from the provided training script in the repo "run_training_synapse.sh"

You can't just run the python file as there are the following variables you must set before running the training script:

```
DATASET_PATH=DATASET

export PYTHONPATH=./
export RESULTS_FOLDER=output_synapse_UNETR_GitHub
export unetr_pp_preprocessed="$DATASET_PATH"/unetr_pp_raw/unetr_pp_raw_data/Task02_Synapse
export unetr_pp_raw_data_base="$DATASET_PATH"/unetr_pp_raw

python unetr_pp/run/run_training.py 3d_fullres unetr_pp_trainer_synapse 2 0
```

**Comment by MOMOANNIE** [comment]
> Hi @MOMOANNIE,
> 
> Please make sure to run the training from the provided training script in the repo "run_training_synapse.sh"
> 
> You can't just run the python file as there are the following variables you must set before running the training script:
> 
> ```
> DATASET_PATH=DATASET
> 
> export PYTHONPATH=./
> export RESULTS_FOLDER=output_synapse_UNETR_GitHub
> export unetr_pp_preprocessed="$DATASET_PATH"/unetr_pp_raw/unetr_pp_raw_data/Task02_Synapse
> export unetr_pp_raw_data_base="$DATASET_PATH"/unetr_pp_raw
> 
> python unetr_pp/run/run_training.py 3d_fullres unetr_pp_trainer_synapse 2 0
> ```
Ok thank you, after running run_training_synapse.sh, there is another problem, as follows:
`   with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/project/DATASET/unetr_pp_preprocessed/Task032/unetr_pp_Plansv2.1_plans_3D.pkl'
`

This is because I did not preprocess my data. If it is my own data, how should I preprocess it?

**Comment by Amshaker** [comment]
You should do it in the same way as [nnFormer](https://github.com/282857341/nnFormer#2-setting-up-the-datasets) setting up the datasets.

**Comment by 4dirveduck** [comment]
Hello, I had the same problem, my folder structure is similarity with https://github.com/Amshaker/unetr_plus_plus/tree/main/unetr_pp   
and i'm running the training script:"bash training_scripts/run_training_synapse.sh
", the problem still exists.
Can you help me to solv the problem?
![111](https://github.com/Amshaker/unetr_plus_plus/assets/101452601/168be654-5b96-4ce3-814b-c30a9c53803a)
![222](https://github.com/Amshaker/unetr_plus_plus/assets/101452601/73a10bfc-9ddf-4640-bad0-974506e4033e)
