### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by chuanqiWen** [Amshaker/unetr_plus_plus#15]
Traceback (most recent call last):
  File "unetr_pp/run/run_training.py", line 173, in <module>
    main()
  File "unetr_pp/run/run_training.py", line 119, in main
    task = convert_id_to_task_name(task_id)
  File "/home/dl207/paper_experiment/unetr_plus_plus/unetr_pp/utilities/task_name_id_conversion.py", line 51, in convert_id_to_task_name
    raise RuntimeError("Could not find a task with the ID %d. Make sure the requested task ID exists and that "
RuntimeError: Could not find a task with the ID 2. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
unetr_pp_preprocessed=DATASET/unetr_pp_raw/unetr_pp_raw_data/Task02_Synapse
RESULTS_FOLDER=output_synapse
unetr_pp_raw_data_base=DATASET/unetr_pp_raw
If something is not right, adapt your environemnt variables.

**Comment by Amshaker** [comment]
Hi,
You should download the provided pre-processed dataset and follow the data structure explained in the README file.
