### ISSUE TITLE
How to compute model's FLOPs ?

### ISSUE THREAD

**Issue by qiaoqiangPro** [Amshaker/unetr_plus_plus#20]
I find this codes in program，MAdds is not equal FLOPs. I want to know how to compute FLOPs in your paper , can you help me? 
print(f"Total trainable parameters: {round(n_parameters * 1e-6, 2)} M")
print(f"MAdds: {round(model_flops * 1e-9, 2)} G")

**Comment by Amshaker** [comment]
Hi,

We computed the FLOPs based on [fvcore library](https://github.com/facebookresearch/fvcore/blob/main/docs/flop_count.md). Please check their documentation for more details.

Best regards,
Abdelrahman.
