### ISSUE TITLE
Swin-UNETR results question

### ISSUE THREAD

**Issue by GYDDHPY** [Amshaker/unetr_plus_plus#24]
Thank you for your great contribution.  I'm really intetested in your work so I tried to do some experiments.
I notice that the Swin-UNETR results shown in Tabel 1 has average dice socre of 83.48. I also tried to implement the model using TransUnet data split but got a much lower results which is only 74. Could you please share some details of the training and testing procedure of the Swin-UNETR model?
Looking forward to your reply.

**Comment by Amshaker** [comment]
Hi @GYDDHPY,


Thank you for showing interest in our work. How do you use TransUnet data? they are 2D slices not 3D voxels. The shared results are based on nnFormer codebase. Basically, we used the same data pre-processing of their repo and replaced the model with swin-unetr model.

Please let me know if you have more questions.

Best regards,
Abdelrahman.

**Comment by GYDDHPY** [comment]
> Hi @GYDDHPY,
> 
> Thank you for showing interest in our work. How do you use TransUnet data? they are 2D slices not 3D voxels. The shared results are based on nnFormer codebase. Basically, we used the same data pre-processing of their repo and replaced the model with swin-unetr model.
> 
> Please let me know if you have more questions.
> 
> Best regards, Abdelrahman.

Thank you for your reply.
I use the official code from Swin-UNETR and 3D data are used for training and testing. I follow the data split method in TransUnet, 18 samples are used as training and the remaining are used for test.  No more modifications are made.
So, you mean your results are based on nnFormer architecture but only the segementation model is replaced to test different model performance? 
Looking forward to your reply.

**Comment by Amshaker** [comment]
Yes, our code is built over the nnFormer codebase. We apply the same pre-processing and evaluation metrics of nnFormer for all methods, including our method to have a fair comparison.

**Comment by 6018203135** [comment]
@GYDDHPY 
Hello, trouble want to ask if you run swinunetr with the unetr++ code only changed the network architecture in it? Or re-download the code specifically designed to run swinunetr?

**Comment by GYDDHPY** [comment]
I directly use the origin code of  SwinUNETR.
