### ISSUE TITLE
Results in BraTs

### ISSUE THREAD

**Issue by qiaoqiangPro** [Amshaker/unetr_plus_plus#25]
Hi, are the results obtained in the paper on the BraTs dataset the test results of a certain fold or the results after a five fold cross validation?
Thank you for your reply

**Comment by Amshaker** [comment]
Hi,

Thank you for your question.

It is a certain fold, please refer to [This file](https://github.com/Amshaker/unetr_plus_plus/blob/main/unetr_pp/training/network_training/unetr_pp_trainer_tumor.py) to know the exact data division for training & testing. We followed this division for all methods in the BRaTs table in our paper.

I hope it is clear now.

Best regards,
Abdelrahman.

**Comment by qiaoqiangPro** [comment]
Thks，so .. no matter the superparameter "fold" is specified 0 or 1 in my training, the data division used is fixed, so I don't need to run 5 fold cross verification, just specify a random fold. Do you think it is right? 
Thank you for your reply

**Comment by 6018203135** [comment]
@qiaoqiangPro  你复现成功了unetr++吗 能加个联系方式吗

**Comment by qiaoqiangPro** [comment]
> 

我加你

**Comment by qiaoqiangPro** [comment]
@6018203135 我加你吧

**Comment by 6018203135** [comment]
@qiaoqiangPro ok qq:
2436281007

**Comment by qiaoqiangPro** [comment]
> @qiaoqiangPro ok qq: 2436281007

没啊

**Comment by qiaoqiangPro** [comment]
@6018203135 搜不到

**Comment by 6018203135** [comment]
@qiaoqiangPro 
不好意思不好意思 2436381007

**Comment by liaochuanlin** [comment]
@qiaoqiangPro 可以加我邮件吗？关于代码有些问题请教

**Comment by liaochuanlin** [comment]
@qiaoqiangPro 2651106983@qq.com

**Comment by WangXiaoXv** [comment]
> @6018203135 我加你吧

可以加个联系方式吗？关于代码有些问题请教
联系方式：qq：2766832657
