### ISSUE TITLE
About processed data

### ISSUE THREAD

**Issue by SanmAIGO** [Amshaker/unetr_plus_plus#26]
Hello author, your work is very excellent. I am learning your work and trying to reproduce your results, but I found the results inconsistent with the data I processed. So for better reproduction results, I want to get the processed data you used, I found that the processed data link in this repo is no longer valid, can you reopen the link?

**Comment by SanmAIGO** [comment]
Looking forward to your reply.

Best regards.
Sanm

**Comment by Amshaker** [comment]
Hi Sanm,

Thank you for your interest in our work.

Yes, we noticed that the links for the pre-processed data are expired. Sorry for this inconvenience.

We will start uploading them again this week.

Thank you,
Abdelrahman.

**Comment by SanmAIGO** [comment]
Thank you for your reply. Looking forward to your data link, which will enable me to better reproduce your work. Thank you for your selfless sharing and wish you a greater academic harvest. 

Best wishes to you
Sanm
