### ISSUE TITLE
the link of preprocessed four datasets are invalid

### ISSUE THREAD

**Issue by qingwang-usc** [Amshaker/unetr_plus_plus#27]
Dear authors:
    I want to download the Synapse dataset, but i found that it has been invalid. Could you help me to solve this problem? Thank you very much.

**Comment by Amshaker** [comment]
Hi @qingwang-usc ,

Please check now. The link for Synapse is updated.

Best regards,
Abdelrahman.

**Comment by qingwang-usc** [comment]
It works. Thank you very much!
