### ISSUE TITLE
No module named 'unetr_pp'

### ISSUE THREAD

**Issue by so-ux** [Amshaker/unetr_plus_plus#29]
I want to use 'nnFormer_plan_and_preprocess.py' to process my dataset, but something is wrong with those messages:
Traceback (most recent call last):
  File ".../unetr_plus_plus-main/unetr_plus_plus-main/unetr_pp/experiment_planning/nnFormer_plan_and_preprocess.py", line 18, in <module>
    import unetr_pp
ModuleNotFoundError: No module named 'unetr_pp'
How can I solve this problem

**Comment by Amshaker** [comment]
Hi @so-ux ,

Thank you for your interest in our work.

Please refer to https://github.com/Amshaker/unetr_plus_plus/issues/12 

Best regards,
Abdelrahman.

**Comment by ForrestFzy** [comment]
This could be a good solution:
`import sys
sys.path.append('/****/****/unetr_plus_plus-main')`
