### ISSUE TITLE
The training time on the Synapse Dataset?

### ISSUE THREAD

**Issue by c-yn** [Amshaker/unetr_plus_plus#3]
Dear author,

Could you pls tell me the training time on the Synapse Dataset and the GPU configuration, e.g., number and type.

Thanks very much.

**Comment by Amshaker** [comment]
Hi @c-yn,

The training time of the Synapse dataset for UNETR++ is ~15 hours using a single A100 40GB GPU. You can also find that and more details about the training in the implementation details section of our paper.

Regards,
Abdelrahman.

**Comment by c-yn** [comment]
> Hi @c-yn,
> 
> The training time of the Synapse dataset for UNETR++ is ~15 hours using a single A100 40GB GPU. You can also find that and more details about the training in the implementation details section of our paper.
> 
> Regards, Abdelrahman.

Thanks for your prompt reply.
