### ISSUE TITLE
About synapse dataset labels

### ISSUE THREAD

**Issue by CamillerFerros** [Amshaker/unetr_plus_plus#30]
Regarding the synapse dataset, there are a total of 13 organs in the labels in the 3D dataset, but there are a total of 8 organs compared in the paper, please ask whether the function of calculating loss during training uses 8 organs or 13 organs, and whether the model output is 13 organs or 8 organs, thank you very much

**Comment by Amshaker** [comment]
Hi @CamillerFerros ,

Yes, there are 13 organs and the output of the model is 13 classes, but the DSC and HD95 are computed based on only 8 organs. Please note that the split for Synapse  (18 + 12) is different from the split for BTCV (24 + 6).
