### ISSUE TITLE
Results on postprocessed or raw output data?

### ISSUE THREAD

**Issue by Leonngm** [Amshaker/unetr_plus_plus#33]
Hi,
thanks four you excellent work.
The codebase does some postprocessing after validation to improve the results. Are your results based on the postprocessed results or without postprocessing?

Thank you!

**Comment by Amshaker** [comment]
Hi @Leonngm ,

Thank you for your interest in our work.

The results we report for UNETR++, as well as all other methods, are after post-processing.

Best regards,
Abdelrahman.

**Comment by Amshaker** [comment]
All the reported results are based on post-processing results to compare with other methods consistently.
