### ISSUE TITLE
ACDC data

### ISSUE THREAD

**Issue by 6018203135** [Amshaker/unetr_plus_plus#38]
Hello author, I'm really sorry, I want to ask a question about the ACDC dataset, the test set used by UNETR++ is 'patient089_frame01', 'patient089_frame10'
Does this count as one? However, there are only 10 imagesTs, the original ACDC dataset is 100, and the images Tr provided by the author have 80 (including 10 validation sets and 70 training sets)

**Comment by Amshaker** [comment]
Hi,

Please be sure about the data you mention in the question, it might be misleading to other researchers :). Why do you mention the data provided by the author is 80?

The data provided by the author (DATASET_Acdc/unetr_pp_raw/unetr_pp_raw_data/Task001_ACDC/imagesTr) is 100 samples, not 80 samples.

<img width="1568" alt="image" src="https://github.com/Amshaker/unetr_plus_plus/assets/108531886/51d4315a-ef7e-4da8-92da-d7b61cfe3bef">

Yes, both frames are counted as one sample. Here are the training and testing samples: https://github.com/Amshaker/unetr_plus_plus/blob/bc6bed1eb2d2d735d5f44740958ef4ea862304a6/unetr_pp/training/network_training/unetr_pp_trainer_acdc.py#L346

Please refer to the paper carefully for more information.

**Comment by 6018203135** [comment]
@Amshaker Disturbed the author! I used the ACDC dataset you provided, trained 1000epoch, and found that the validation set results in summary.json in the validation_raw_postprocessed file and the predict_simple.py file I re-executed with the trained model_best.model to generate predictive test labels inference_ acdc.py the results are different, in the second way my accuracy is only 0.02, the result is a bit outrageous, I want to ask you, where is the problem? Thank you so much! Here are the results of my experiment. 
(1) summary.json result: 
 "reference": "/root/autodl-tmp/data/DATASET/nnFormer_preprocessed/Task001_ACDC/gt_segmentations/patient095_frame12.nii.gz",
                "test": "/root/autodl-tmp/data/DATASET/nnFormer_trained_models/unetr_pp/3d_fullres/Task001_ACDC/unetr_pp_trainer_acdc__unetr_pp_Plansv2.1/fold_0/validation_raw_postprocessed/patient095_frame12.nii.gz"
            }
        ],
        "mean": {
            "1": {
                "Accuracy": 0.9956343624672263,
                "Dice": 0.8133244859950842,
                "False Discovery Rate": 0.29189203000206926,
                "False Negative Rate": 0.023254209549772958,
                "False Omission Rate": 0.00016207729197368435,
                "False Positive Rate": 0.004265137268728636,
                "Jaccard": 0.6985343189273674,
                "Negative Predictive Value": 0.9998379227080264,
                "Precision": 0.7081079699979307,
                "Recall": 0.9767457904502269,
                "Total Positives Reference": 6604.7,
                "Total Positives Test": 8687.0,
                "True Negative Rate": 0.9957348627312712
            },
            "2": {
                "Accuracy": 0.995435524571116,
                "Dice": 0.8299434282979716,
                "False Discovery Rate": 0.1963606665798471,
                "False Negative Rate": 0.1402798206193858,
                "False Omission Rate": 0.0018131184462030017,
                "False Positive Rate": 0.00281533126728819,
                "Jaccard": 0.7109718398988019,
                "Negative Predictive Value": 0.998186881553797,
                "Precision": 0.8036393334201529,
                "Recall": 0.8597201793806143,
                "Total Positives Reference": 6715.075,
                "Total Positives Test": 7230.4,
                "True Negative Rate": 0.9971846687327117
            },
            "3": {
                "Accuracy": 0.9984309371979455,
                "Dice": 0.9426565408123958,
                "False Discovery Rate": 0.10098973894673105,
                "False Negative Rate": 0.006893134954023464,
                "False Omission Rate": 0.0001216667757356525,
                "False Positive Rate": 0.001473658952147136,
                "Jaccard": 0.8932048015679367,
                "Negative Predictive Value": 0.9998783332242642,
                "Precision": 0.899010261053269,
                "Recall": 0.9931068650459765,
                "Total Positives Reference": 8219.25,
                "Total Positives Test": 8895.475,
                "True Negative Rate": 0.9985263410478528
            }
        }
    },
(2) Method 2 dice_pre.txt result:
********************
patient002_frame01.nii.gz
hd_rv: 82.2922
hd_myo: 108.1219
hd_lv: 106.4815
********************
patient002_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0204
Dice_lv: 0.0523
hd_rv: 82.2922
hd_myo: 108.1219
hd_lv: 106.4815
********************
********************
patient002_frame12.nii.gz
hd_rv: 177.4035
hd_myo: 114.3724
hd_lv: 112.4375
********************
patient002_frame12.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0103
Dice_lv: 0.0641
hd_rv: 177.4035
hd_myo: 114.3724
hd_lv: 112.4375
********************
********************
patient003_frame01.nii.gz
hd_rv: 109.4372
hd_myo: 110.0000
hd_lv: 88.5641
********************
patient003_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0209
Dice_lv: 0.0385
hd_rv: 109.4372
hd_myo: 110.0000
hd_lv: 88.5641
********************
********************
patient003_frame15.nii.gz
hd_rv: 107.0794
hd_myo: 110.8569
hd_lv: 91.2483
********************
patient003_frame15.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0328
Dice_lv: 0.0433
hd_rv: 107.0794
hd_myo: 110.8569
hd_lv: 91.2483
********************
********************
patient008_frame01.nii.gz
hd_rv: 65.2821
hd_myo: 73.0274
hd_lv: 111.9013
********************
patient008_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0128
Dice_lv: 0.0000
hd_rv: 65.2821
hd_myo: 73.0274
hd_lv: 111.9013
********************
********************
patient008_frame13.nii.gz
hd_rv: 62.0322
hd_myo: 74.6753
hd_lv: 112.2854
********************
patient008_frame13.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0027
Dice_lv: 0.0000
hd_rv: 62.0322
hd_myo: 74.6753
hd_lv: 112.2854
********************
********************
patient009_frame01.nii.gz
hd_rv: 91.6510
hd_myo: 80.1857
hd_lv: 97.2528
********************
patient009_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0273
Dice_lv: 0.0263
hd_rv: 91.6510
hd_myo: 80.1857
hd_lv: 97.2528
********************
********************
patient009_frame13.nii.gz
hd_rv: 68.1337
hd_myo: 76.5692
hd_lv: 100.3444
********************
patient009_frame13.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0538
Dice_lv: 0.0401
hd_rv: 68.1337
hd_myo: 76.5692
hd_lv: 100.3444
********************
********************
patient012_frame01.nii.gz
hd_rv: 67.4722
hd_myo: 99.8677
hd_lv: 100.7720
********************
patient012_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0052
Dice_lv: 0.0148
hd_rv: 67.4722
hd_myo: 99.8677
hd_lv: 100.7720
********************
********************
patient012_frame13.nii.gz
hd_rv: 61.6141
hd_myo: 102.4920
hd_lv: 101.1046
********************
patient012_frame13.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0169
Dice_lv: 0.0550
hd_rv: 61.6141
hd_myo: 102.4920
hd_lv: 101.1046
********************
********************
patient014_frame01.nii.gz
hd_rv: 41.8999
hd_myo: 92.3797
hd_lv: 76.6825
********************
patient014_frame01.nii.gz
Dice_rv: 0.0059
Dice_myo: 0.0189
Dice_lv: 0.0392
hd_rv: 41.8999
hd_myo: 92.3797
hd_lv: 76.6825
********************
********************
patient014_frame13.nii.gz
hd_rv: 37.2424
hd_myo: 93.0261
hd_lv: 82.4742
********************
patient014_frame13.nii.gz
Dice_rv: 0.0073
Dice_myo: 0.0292
Dice_lv: 0.0201
hd_rv: 37.2424
hd_myo: 93.0261
hd_lv: 82.4742
********************
********************
patient017_frame01.nii.gz
hd_rv: 75.0626
hd_myo: 89.7352
hd_lv: 104.4079
********************
patient017_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0029
Dice_lv: 0.0060
hd_rv: 75.0626
hd_myo: 89.7352
hd_lv: 104.4079
********************
********************
patient017_frame09.nii.gz
hd_rv: 73.0007
hd_myo: 93.9683
hd_lv: 108.6508
********************
patient017_frame09.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0073
Dice_lv: 0.0022
hd_rv: 73.0007
hd_myo: 93.9683
hd_lv: 108.6508
********************
********************
patient024_frame01.nii.gz
hd_rv: 68.4792
hd_myo: 90.4135
hd_lv: 107.5407
********************
patient024_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0514
Dice_lv: 0.0057
hd_rv: 68.4792
hd_myo: 90.4135
hd_lv: 107.5407
********************
********************
patient024_frame09.nii.gz
hd_rv: 33.6155
hd_myo: 95.4018
hd_lv: 113.2961
********************
patient024_frame09.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0018
Dice_lv: 0.0135
hd_rv: 33.6155
hd_myo: 95.4018
hd_lv: 113.2961
********************
********************
patient042_frame01.nii.gz
hd_rv: 69.6419
hd_myo: 120.7951
hd_lv: 110.6097
********************
patient042_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0000
Dice_lv: 0.0229
hd_rv: 69.6419
hd_myo: 120.7951
hd_lv: 110.6097
********************
********************
patient042_frame16.nii.gz
hd_rv: 57.1034
hd_myo: 120.7442
hd_lv: 114.2650
********************
patient042_frame16.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0000
Dice_lv: 0.0531
hd_rv: 57.1034
hd_myo: 120.7442
hd_lv: 114.2650
********************
********************
patient048_frame01.nii.gz
hd_rv: 66.6059
hd_myo: 81.9582
hd_lv: 105.7329
********************
patient048_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0003
Dice_lv: 0.0477
hd_rv: 66.6059
hd_myo: 81.9582
hd_lv: 105.7329
********************
********************
patient048_frame08.nii.gz
hd_rv: 65.4458
hd_myo: 83.0602
hd_lv: 112.8105
********************
patient048_frame08.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0046
Dice_lv: 0.0126
hd_rv: 65.4458
hd_myo: 83.0602
hd_lv: 112.8105
********************
********************
patient049_frame01.nii.gz
hd_rv: 53.1644
hd_myo: 89.5637
hd_lv: 128.9333
********************
patient049_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0430
Dice_lv: 0.0313
hd_rv: 53.1644
hd_myo: 89.5637
hd_lv: 128.9333
********************
********************
patient049_frame11.nii.gz
hd_rv: 101.0940
hd_myo: 92.1358
hd_lv: 131.3324
********************
patient049_frame11.nii.gz
Dice_rv: 0.0013
Dice_myo: 0.0188
Dice_lv: 0.0380
hd_rv: 101.0940
hd_myo: 92.1358
hd_lv: 131.3324
********************
********************
patient053_frame01.nii.gz
hd_rv: 122.7467
hd_myo: 96.3878
hd_lv: 127.2360
********************
patient053_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0728
Dice_lv: 0.0079
hd_rv: 122.7467
hd_myo: 96.3878
hd_lv: 127.2360
********************
********************
patient053_frame12.nii.gz
hd_rv: 122.7096
hd_myo: 98.8683
hd_lv: 133.4103
********************
patient053_frame12.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0022
Dice_lv: 0.0090
hd_rv: 122.7096
hd_myo: 98.8683
hd_lv: 133.4103
********************
********************
patient055_frame01.nii.gz
hd_rv: 114.0702
hd_myo: 103.0825
hd_lv: 102.4353
********************
patient055_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0032
Dice_lv: 0.0117
hd_rv: 114.0702
hd_myo: 103.0825
hd_lv: 102.4353
********************
********************
patient055_frame10.nii.gz
hd_rv: 47.6707
hd_myo: 107.0091
hd_lv: 105.7852
********************
patient055_frame10.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0055
Dice_lv: 0.0000
hd_rv: 47.6707
hd_myo: 107.0091
hd_lv: 105.7852
********************
********************
patient064_frame01.nii.gz
hd_rv: 74.9667
hd_myo: 107.5156
hd_lv: 114.1464
********************
patient064_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0124
Dice_lv: 0.0682
hd_rv: 74.9667
hd_myo: 107.5156
hd_lv: 114.1464
********************
********************
patient064_frame12.nii.gz
hd_rv: 68.7677
hd_myo: 109.0431
hd_lv: 117.1108
********************
patient064_frame12.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0351
Dice_lv: 0.0673
hd_rv: 68.7677
hd_myo: 109.0431
hd_lv: 117.1108
********************
********************
patient067_frame01.nii.gz
hd_rv: 67.9412
hd_myo: 100.1714
hd_lv: 101.1200
********************
patient067_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0353
Dice_lv: 0.1424
hd_rv: 67.9412
hd_myo: 100.1714
hd_lv: 101.1200
********************
********************
patient067_frame10.nii.gz
hd_rv: 67.9412
hd_myo: 103.9519
hd_lv: 99.0656
********************
patient067_frame10.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0799
Dice_lv: 0.1669
hd_rv: 67.9412
hd_myo: 103.9519
hd_lv: 99.0656
********************
********************
patient079_frame01.nii.gz
hd_rv: 80.4301
hd_myo: 121.6643
hd_lv: 112.8273
********************
patient079_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0378
Dice_lv: 0.0234
hd_rv: 80.4301
hd_myo: 121.6643
hd_lv: 112.8273
********************
********************
patient079_frame11.nii.gz
hd_rv: 51.3936
hd_myo: 127.2053
hd_lv: 123.0197
********************
patient079_frame11.nii.gz
Dice_rv: 0.0006
Dice_myo: 0.0086
Dice_lv: 0.0444
hd_rv: 51.3936
hd_myo: 127.2053
hd_lv: 123.0197
********************
********************
patient081_frame01.nii.gz
hd_rv: 71.5612
hd_myo: 95.4125
hd_lv: 99.2824
********************
patient081_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0041
Dice_lv: 0.0053
hd_rv: 71.5612
hd_myo: 95.4125
hd_lv: 99.2824
********************
********************
patient081_frame07.nii.gz
hd_rv: 51.4451
hd_myo: 97.0000
hd_lv: 103.8220
********************
patient081_frame07.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0085
Dice_lv: 0.0018
hd_rv: 51.4451
hd_myo: 97.0000
hd_lv: 103.8220
********************
********************
patient088_frame01.nii.gz
hd_rv: 60.8169
hd_myo: 99.6218
hd_lv: 93.9191
********************
patient088_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0000
Dice_lv: 0.0135
hd_rv: 60.8169
hd_myo: 99.6218
hd_lv: 93.9191
********************
********************
patient088_frame12.nii.gz
hd_rv: 27.4773
hd_myo: 100.9121
hd_lv: 100.0620
********************
patient088_frame12.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0000
Dice_lv: 0.0031
hd_rv: 27.4773
hd_myo: 100.9121
hd_lv: 100.0620
********************
********************
patient092_frame01.nii.gz
hd_rv: 19.0526
hd_myo: 78.1521
hd_lv: 103.9016
********************
patient092_frame01.nii.gz
Dice_rv: 0.0077
Dice_myo: 0.0209
Dice_lv: 0.0439
hd_rv: 19.0526
hd_myo: 78.1521
hd_lv: 103.9016
********************
********************
patient092_frame06.nii.gz
hd_rv: 21.5430
hd_myo: 76.9571
hd_lv: 107.2476
********************
patient092_frame06.nii.gz
Dice_rv: 0.0250
Dice_myo: 0.1117
Dice_lv: 0.0654
hd_rv: 21.5430
hd_myo: 76.9571
hd_lv: 107.2476
********************
********************
patient095_frame01.nii.gz
hd_rv: 23.3463
hd_myo: 36.8170
hd_lv: 106.4070
********************
patient095_frame01.nii.gz
Dice_rv: 0.0039
Dice_myo: 0.0014
Dice_lv: 0.0530
hd_rv: 23.3463
hd_myo: 36.8170
hd_lv: 106.4070
********************
********************
patient095_frame12.nii.gz
hd_rv: 30.2655
hd_myo: 29.3019
hd_lv: 112.3871
********************
patient095_frame12.nii.gz
Dice_rv: 0.0076
Dice_myo: 0.2153
Dice_lv: 0.1232
hd_rv: 30.2655
hd_myo: 29.3019
hd_lv: 112.3871
********************
********************
Mean_Dice
Dice_rv0.0014833411610974427
Dice_myo0.025901555917205978
Dice_lv0.036925817218667785
Mean_HD
HD_rv68.9724658656119
HD_myo94.56059658967824
HD_lv107.05783058276431
********************
avg_hd:90.19696434601815
DSC:0.02143690476565707
HD:90.19696434601815

**Comment by WangXiaoXv** [comment]
> @Amshaker作者干扰了！我使用了您提供的ACDC数据集，训练了1000epoch，发现验证集结果在validation_raw_postprocessed文件中的summary.json和我用训练好的model_best.model重新执行的predict_simple.py文件中，以生成预测标签测试inference_ acdc。py的结果不一样，第二种方式我的准确率只有0.02，结果有点离谱，我想问一下，问题出在哪里？太感谢了！这是我的实验结果。（ 1 ）summary.json 结果： “reference”：“/root/autodl-tmp/data/DATASET/nnFormer_preprocessed/Task001_ACDC/gt_segmentations/patent095_frame12.nii.gz”， “test”：“/root/autodl-tmp/data /DATASET /nnFormer_trained_models/unetr_pp/3d_fullres/Task001_ACDC/unetr_pp_trainer_acdc__unetr_pp_Plansv2.1/fold_0/validation_raw_postprocessed/patent095_frame12.nii.gz" } ], "干": { "1": { "准确性": 0.995634362467第226期第三章， “死亡” ：0.8133244859950842， “错误发现率”：0.29189203000206926， “假阴性率”：0.023254209549772958， “错误漏率”：0.00016207729197368435，“假 阳性率” ：0.00426513726 8728636，“杰卡德”：0。 6985343189273674, "负预测值" : 0.9998379227080264, "精度": 0.7081079699979307， "反应率"：0.9767457904502269， " 总进攻参考"：6604.7， " 总进攻测试"：8687.0， "真阴性率"：0.9957348627312712 }， “ 2”：{ “准确度” ：0.9954 35524571116, "骰子": 0.8299434282979716, “错误发现率”：0.1963606665798471， “假阴性率”：0.1402798206193858， “错误遗漏率”：0.0018131184462030017 ，“假 积极率”：0.00281533126728819， “杰卡德”：0.71097 18398988019 , "负预测值": 0.998186881553797, "精度": 0.8036393334201529， "感知率"：0.8597201793806143， " 总猛测"：6715.075， "总猛测试"：7230.4， "真阳性率"：0.9971846687327 117 }， “3” ：{ “准确度”：0.99 84309371979455, “骰子”: 0.9426565408123958, “错误发现率”：0.10098973894673105， “假阴性率”：0.006893134954023464， “错误遗漏率”：0.000121666 7757356525， “误报率”：0.001473658952147136， “杰卡德”：0.8932048015679367， “阴性预测值”：0.9998783332242642， “精度”：0.899010261053269， “认知率”：0.993106865 0459765， “ 总前进参考”：8219.25， “总积极测试”：8895.475， “真负率”： 0.9985263410478528 } } }， （2）方法2 dice_pre.txt 结果：
> 
> 患者002_frame01.nii.gz hd_rv：82.2922 hd_myo：108.1219 hd_lv：106.4815
> 
> 患者002_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0204 Dice_lv：0.0523 hd_rv：82.2922 hd_myo：108.1219 hd_lv：106.4815
> 
> 患者002_frame12.nii.gz hd_rv：177.4035 hd_myo：114.3724 hd_lv：112.4375
> 
> 患者002_frame12.nii.gz Dice_rv：0.0000 Dice_myo：0.0103 Dice_lv：0.0641 hd_rv：177.4035 hd_myo：114.3724 hd_lv：112.4375
> 
> 患者003_frame01.nii.gz hd_rv：109.4372 hd_myo：110.0000 hd_lv：88.5641
> 
> 患者003_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0209 Dice_lv：0.0385 hd_rv：109.4372 hd_myo：110.0000 hd_lv：88.5641
> 
> 患者003_frame15.nii.gz hd_rv：107.0794 hd_myo：110.8569 hd_lv：91.2483
> 
> 患者003_frame15.nii.gz Dice_rv：0.0000 Dice_myo：0.0328 Dice_lv：0.0433 hd_rv：107.0794 hd_myo：110.8569 hd_lv：91.2483
> 
> 患者008_frame01.nii.gz hd_rv：65.2821 hd_myo：73.0274 hd_lv：111.9013
> 
> 患者008_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0128 Dice_lv：0.0000 hd_rv：65.2821 hd_myo：73.0274 hd_lv：111.9013
> 
> 患者008_frame13.nii.gz hd_rv：62.0322 hd_myo：74.6753 hd_lv：112.2854
> 
> 患者008_frame13.nii.gz Dice_rv：0.0000 Dice_myo：0.0027 Dice_lv：0.0000 hd_rv：62.0322 hd_myo：74.6753 hd_lv：112.2854
> 
> 患者009_frame01.nii.gz hd_rv：91.6510 hd_myo：80.1857 hd_lv：97.2528
> 
> 患者009_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0273 Dice_lv：0.0263 hd_rv：91.6510 hd_myo：80.1857 hd_lv：97.2528
> 
> 患者009_frame13.nii.gz hd_rv：68.1337 hd_myo：76.5692 hd_lv：100.3444
> 
> 患者009_frame13.nii.gz Dice_rv：0.0000 Dice_myo：0.0538 Dice_lv：0.0401 hd_rv：68.1337 hd_myo：76.5692 hd_lv：100.3444
> 
> 患者012_frame01.nii.gz hd_rv：67.4722 hd_myo：99.8677 hd_lv：100.7720
> 
> 患者012_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0052 Dice_lv：0.0148 hd_rv：67.4722 hd_myo：99.8677 hd_lv：100.7720
> 
> 患者012_frame13.nii.gz hd_rv：61.6141 hd_myo：102.4920 hd_lv：101.1046
> 
> 患者012_frame13.nii.gz Dice_rv：0.0000 Dice_myo：0.0169 Dice_lv：0.0550 hd_rv：61.6141 hd_myo：102.4920 hd_lv：101.1046
> 
> 患者014_frame01.nii.gz hd_rv：41.8999 hd_myo：92.3797 hd_lv：76.6825
> 
> 患者014_frame01.nii.gz Dice_rv：0.0059 Dice_myo：0.0189 Dice_lv：0.0392 hd_rv：41.8999 hd_myo：92.3797 hd_lv：76.6825
> 
> 患者014_frame13.nii.gz hd_rv：37.2424 hd_myo：93.0261 hd_lv：82.4742
> 
> 患者014_frame13.nii.gz Dice_rv：0.0073 Dice_myo：0.0292 Dice_lv：0.0201 hd_rv：37.2424 hd_myo：93.0261 hd_lv：82.4742
> 
> 患者017_frame01.nii.gz hd_rv：75.0626 hd_myo：89.7352 hd_lv：104.4079
> 
> 患者017_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0029 Dice_lv：0.0060 hd_rv：75.0626 hd_myo：89.7352 hd_lv：104.4079
> 
> 患者017_frame09.nii.gz hd_rv：73.0007 hd_myo：93.9683 hd_lv：108.6508
> 
> 患者017_frame09.nii.gz Dice_rv：0.0000 Dice_myo：0.0073 Dice_lv：0.0022 hd_rv：73.0007 hd_myo：93.9683 hd_lv：108.6508
> 
> 患者024_frame01.nii.gz hd_rv：68.4792 hd_myo：90.4135 hd_lv：107.5407
> 
> 患者024_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0514 Dice_lv：0.0057 hd_rv：68.4792 hd_myo：90.4135 hd_lv：107.5407
> 
> 患者024_frame09.nii.gz hd_rv：33.6155 hd_myo：95.4018 hd_lv：113.2961
> 
> 患者024_frame09.nii.gz Dice_rv：0.0000 Dice_myo：0.0018 Dice_lv：0.0135 hd_rv：33.6155 hd_myo：95.4018 hd_lv：113.2961
> 
> 患者042_frame01.nii.gz hd_rv：69.6419 hd_myo：120.7951 hd_lv：110.6097
> 
> 患者042_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0000 Dice_lv：0.0229 hd_rv：69.6419 hd_myo：120.7951 hd_lv：110.6097
> 
> 患者042_frame16.nii.gz hd_rv：57.1034 hd_myo：120.7442 hd_lv：114.2650
> 
> 患者042_frame16.nii.gz Dice_rv：0.0000 Dice_myo：0.0000 Dice_lv：0.0531 hd_rv：57.1034 hd_myo：120.7442 hd_lv：114.2650
> 
> 患者048_frame01.nii.gz hd_rv：66.6059 hd_myo：81.9582 hd_lv：105.7329
> 
> 患者048_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0003 Dice_lv：0.0477 hd_rv：66.6059 hd_myo：81.9582 hd_lv：105.7329
> 
> 患者048_frame08.nii.gz hd_rv：65.4458 hd_myo：83.0602 hd_lv：112.8105
> 
> 患者048_frame08.nii.gz Dice_rv：0.0000 Dice_myo：0.0046 Dice_lv：0.0126 hd_rv：65.4458 hd_myo：83.0602 hd_lv：112.8105
> 
> 患者049_frame01.nii.gz hd_rv：53.1644 hd_myo：89.5637 hd_lv：128.9333
> 
> 患者049_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0430 Dice_lv：0.0313 hd_rv：53.1644 hd_myo：89.5637 hd_lv：128.9333
> 
> 患者049_frame11.nii.gz hd_rv：101.0940 hd_myo：92.1358 hd_lv：131.3324
> 
> 患者049_frame11.nii.gz Dice_rv：0.0013 Dice_myo：0.0188 Dice_lv：0.0380 hd_rv：101.0940 hd_myo：92.1358 hd_lv：131.3324
> 
> 患者053_frame01.nii.gz hd_rv：122.7467 hd_myo：96.3878 hd_lv：127.2360
> 
> 患者053_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0728 Dice_lv：0.0079 hd_rv：122.7467 hd_myo：96.3878 hd_lv：127.2360
> 
> 患者053_frame12.nii.gz hd_rv：122.7096 hd_myo：98.8683 hd_lv：133.4103
> 
> 患者053_frame12.nii.gz Dice_rv：0.0000 Dice_myo：0.0022 Dice_lv：0.0090 hd_rv：122.7096 hd_myo：98.8683 hd_lv：133.4103
> 
> 患者055_frame01.nii.gz hd_rv：114.0702 hd_myo：103.0825 hd_lv：102.4353
> 
> 患者055_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0032 Dice_lv：0.0117 hd_rv：114.0702 hd_myo：103.0825 hd_lv：102.4353
> 
> 患者055_frame10.nii.gz hd_rv：47.6707 hd_myo：107.0091 hd_lv：105.7852
> 
> 患者055_frame10.nii.gz Dice_rv：0.0000 Dice_myo：0.0055 Dice_lv：0.0000 hd_rv：47.6707 hd_myo：107.0091 hd_lv：105.7852
> 
> 患者064_frame01.nii.gz hd_rv：74.9667 hd_myo：107.5156 hd_lv：114.1464
> 
> 患者064_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0124 Dice_lv：0.0682 hd_rv：74.9667 hd_myo：107.5156 hd_lv：114.1464
> 
> 患者064_frame12.nii.gz hd_rv：68.7677 hd_myo：109.0431 hd_lv：117.1108
> 
> 患者064_frame12.nii.gz Dice_rv：0.0000 Dice_myo：0.0351 Dice_lv：0.0673 hd_rv：68.7677 hd_myo：109.0431 hd_lv：117.1108
> 
> 患者067_frame01.nii.gz hd_rv：67.9412 hd_myo：100.1714 hd_lv：101.1200
> 
> 患者067_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0353 Dice_lv：0.1424 hd_rv：67.9412 hd_myo：100.1714 hd_lv：101.1200
> 
> 患者067_frame10.nii.gz hd_rv：67.9412 hd_myo：103.9519 hd_lv：99.0656
> 
> 患者067_frame10.nii.gz Dice_rv：0.0000 Dice_myo：0.0799 Dice_lv：0.1669 hd_rv：67.9412 hd_myo：103.9519 hd_lv：99.0656
> 
> 患者079_frame01.nii.gz hd_rv：80.4301 hd_myo：121.6643 hd_lv：112.8273
> 
> 患者079_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0378 Dice_lv：0.0234 hd_rv：80.4301 hd_myo：121.6643 hd_lv：112.8273
> 
> 患者079_frame11.nii.gz hd_rv：51.3936 hd_myo：127.2053 hd_lv：123.0197
> 
> 患者079_frame11.nii.gz Dice_rv：0.0006 Dice_myo：0.0086 Dice_lv：0.0444 hd_rv：51.3936 hd_myo：127.2053 hd_lv：123.0197
> 
> 患者081_frame01.nii.gz hd_rv：71.5612 hd_myo：95.4125 hd_lv：99.2824
> 
> 患者081_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0041 Dice_lv：0.0053 hd_rv：71.5612 hd_myo：95.4125 hd_lv：99.2824
> 
> 患者081_frame07.nii.gz hd_rv：51.4451 hd_myo：97.0000 hd_lv：103.8220
> 
> 患者081_frame07.nii.gz Dice_rv：0.0000 Dice_myo：0.0085 Dice_lv：0.0018 hd_rv：51.4451 hd_myo：97.0000 hd_lv：103.8220
> 
> 患者088_frame01.nii.gz hd_rv：60.8169 hd_myo：99.6218 hd_lv：93.9191
> 
> 患者088_frame01.nii.gz Dice_rv：0.0000 Dice_myo：0.0000 Dice_lv：0.0135 hd_rv：60.8169 hd_myo：99.6218 hd_lv：93.9191
> 
> 患者088_frame12.nii.gz hd_rv：27.4773 hd_myo：100.9121 hd_lv：100.0620
> 
> 患者088_frame12.nii.gz Dice_rv：0.0000 Dice_myo：0.0000 Dice_lv：0.0031 hd_rv：27.4773 hd_myo：100.9121 hd_lv：100.0620
> 
> 患者092_frame01.nii.gz hd_rv：19.0526 hd_myo：78.1521 hd_lv：103.9016
> 
> 患者092_frame01.nii.gz Dice_rv：0.0077 Dice_myo：0.0209 Dice_lv：0.0439 hd_rv：19.0526 hd_myo：78.1521 hd_lv：103.9016
> 
> 患者092_frame06.nii.gz hd_rv：21.5430 hd_myo：76.9571 hd_lv：107.2476
> 
> 患者092_frame06.nii.gz Dice_rv：0.0250 Dice_myo：0.1117 Dice_lv：0.0654 hd_rv：21.5430 hd_myo：76.9571 hd_lv：107.2476
> 
> 患者095_frame01.nii.gz hd_rv：23.3463 hd_myo：36.8170 hd_lv：106.4070
> 
> 患者095_frame01.nii.gz Dice_rv：0.0039 Dice_myo：0.0014 Dice_lv：0.0530 hd_rv：23.3463 hd_myo：36.8170 hd_lv：106.4070
> 
> 患者095_frame12.nii.gz hd_rv：30.2655 hd_myo：29.3019 hd_lv：112.3871
> 
> 患者095_frame12.nii.gz Dice_rv：0.0076 Dice_myo：0.2153 Dice_lv：0.1232 hd_rv：30.2655 hd_myo：29.3019 hd_lv：112.3871
> 
> Mean_Dice Dice_rv0.0014833411610974427 Dice_myo0.025901555917205978 Dice_lv0.036925817218667785 Mean_HD HD_rv68.9724658656119 HD_myo94.56059658967824 HD_lv 107.05783058276431
> 
> avg_hd:90.19696434601815 DSC:0.02143690476565707 高清:90.19696434601815

您好，我遇到与您相似的问题，可以加一下联系方式询问关于复现的问题吗？非常感谢！！、
