### ISSUE TITLE
About the visualization in the paper

### ISSUE THREAD

**Issue by Jason7282** [Amshaker/unetr_plus_plus#4]
Dear authors, I am very interested in your work and impressed by the visualization in your paper (e.g. Figure 1 left and Figure 4), could you please provide the code for these 3D and 2D visualization? Thank you very much.

**Comment by Amshaker** [comment]
Hi @Jason7282,

Thank you for showing interest in our work.

There is no code for the 2D or 3D visualizations. The figures can be generated using [3D Slicer](https://www.slicer.org/) or any 3D visualization tool. You need to provide the software with the input image and the predictions as _.nii.gz_  and that's it. Check this [tutorial](https://slicer.readthedocs.io/en/latest/user_guide/image_segmentation.html), it is pretty nice and easy to follow.

Please let me know if you have more questions.

Best regards,
Abdelrahman.

**Comment by QiaoXiao7282** [comment]
Thanks for your reply. Seems very cool. In Figure 4, are they also generated in 3D Slicer? and the colors in different organs can also be chosen in this tool?

**Comment by Amshaker** [comment]
Yes, Figure. 4 is also generated using 3D Slicer. You can choose a color palette or choose specific colors and map them to the labels of the predictions.

**Comment by QiaoXiao7282** [comment]
Thank you so much for your thoughtful reply.
