### ISSUE TITLE
SA and CA concatenated or summed?

### ISSUE THREAD

**Issue by Leonngm** [Amshaker/unetr_plus_plus#40]
Hi all,

in the paper your state that you perform a sum fusion of the spatial and channel attention features. In your code however you use a linear layer to half the sizes and then simply concatenate them.

Which of the two methods did you use to actually produce the results that you mentioned?

Thank you.

Best regards,
Leon

**Comment by Amshaker** [comment]
Hi @Leonngm ,

Thank you for your question.

The results are with some fusion as stated in the paper. However, both ways work well with minor difference in accuracy ~0.1.

Best regards,
Abdelrahman.
