### ISSUE TITLE
visualization and result

### ISSUE THREAD

**Issue by tanbuinhat** [Amshaker/unetr_plus_plus#45]
Hi, can you public the final result of your model? Thank you so much.

**Comment by Amshaker** [comment]
Hi @tanbuinhat ,

The data is visualized using the [3D Slicer software](https://www.slicer.org/).

Best regards,
Abdelrahman.

**Comment by tanbuinhat** [comment]
Thank you so much. I am much appreciated your reply!

Best wishes,
Nhat-Tan Bui.

**Comment by tanbuinhat** [comment]
Thank you so much. I am much appreciated your reply!

Best wishes,
Nhat-Tan Bui.
