### ISSUE TITLE
about acdc

### ISSUE THREAD

**Issue by 6018203135** [Amshaker/unetr_plus_plus#46]
Disturbed the author! I used the ACDC dataset you provided, trained 1000epoch, and found that the validation set results in summary.json in the validation_raw_postprocessed file and the predict_simple.py file I re-executed with the trained model_best.model to generate predictive test labels inference_ acdc.py the results are different, in the second way my accuracy is only 0.02, the result is a bit outrageous, I want to ask you, where is the problem? Thank you so much! Here are the results of my experiment.
(1) summary.json result:
"reference": "/root/autodl-tmp/data/DATASET/nnFormer_preprocessed/Task001_ACDC/gt_segmentations/patient095_frame12.nii.gz",
"test": "/root/autodl-tmp/data/DATASET/nnFormer_trained_models/unetr_pp/3d_fullres/Task001_ACDC/unetr_pp_trainer_acdc__unetr_pp_Plansv2.1/fold_0/validation_raw_postprocessed/patient095_frame12.nii.gz"
}
],
"mean": {
"1": {
"Accuracy": 0.9956343624672263,
"Dice": 0.8133244859950842,
"False Discovery Rate": 0.29189203000206926,
"False Negative Rate": 0.023254209549772958,
"False Omission Rate": 0.00016207729197368435,
"False Positive Rate": 0.004265137268728636,
"Jaccard": 0.6985343189273674,
"Negative Predictive Value": 0.9998379227080264,
"Precision": 0.7081079699979307,
"Recall": 0.9767457904502269,
"Total Positives Reference": 6604.7,
"Total Positives Test": 8687.0,
"True Negative Rate": 0.9957348627312712
},
"2": {
"Accuracy": 0.995435524571116,
"Dice": 0.8299434282979716,
"False Discovery Rate": 0.1963606665798471,
"False Negative Rate": 0.1402798206193858,
"False Omission Rate": 0.0018131184462030017,
"False Positive Rate": 0.00281533126728819,
"Jaccard": 0.7109718398988019,
"Negative Predictive Value": 0.998186881553797,
"Precision": 0.8036393334201529,
"Recall": 0.8597201793806143,
"Total Positives Reference": 6715.075,
"Total Positives Test": 7230.4,
"True Negative Rate": 0.9971846687327117
},
"3": {
"Accuracy": 0.9984309371979455,
"Dice": 0.9426565408123958,
"False Discovery Rate": 0.10098973894673105,
"False Negative Rate": 0.006893134954023464,
"False Omission Rate": 0.0001216667757356525,
"False Positive Rate": 0.001473658952147136,
"Jaccard": 0.8932048015679367,
"Negative Predictive Value": 0.9998783332242642,
"Precision": 0.899010261053269,
"Recall": 0.9931068650459765,
"Total Positives Reference": 8219.25,
"Total Positives Test": 8895.475,
"True Negative Rate": 0.9985263410478528
}
}
},
(2) Method 2 dice_pre.txt result:

patient002_frame01.nii.gz
hd_rv: 82.2922
hd_myo: 108.1219
hd_lv: 106.4815

patient002_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0204
Dice_lv: 0.0523
hd_rv: 82.2922
hd_myo: 108.1219
hd_lv: 106.4815

patient002_frame12.nii.gz
hd_rv: 177.4035
hd_myo: 114.3724
hd_lv: 112.4375

patient002_frame12.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0103
Dice_lv: 0.0641
hd_rv: 177.4035
hd_myo: 114.3724
hd_lv: 112.4375

patient003_frame01.nii.gz
hd_rv: 109.4372
hd_myo: 110.0000
hd_lv: 88.5641

patient003_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0209
Dice_lv: 0.0385
hd_rv: 109.4372
hd_myo: 110.0000
hd_lv: 88.5641

patient003_frame15.nii.gz
hd_rv: 107.0794
hd_myo: 110.8569
hd_lv: 91.2483

patient003_frame15.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0328
Dice_lv: 0.0433
hd_rv: 107.0794
hd_myo: 110.8569
hd_lv: 91.2483

patient008_frame01.nii.gz
hd_rv: 65.2821
hd_myo: 73.0274
hd_lv: 111.9013

patient008_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0128
Dice_lv: 0.0000
hd_rv: 65.2821
hd_myo: 73.0274
hd_lv: 111.9013

patient008_frame13.nii.gz
hd_rv: 62.0322
hd_myo: 74.6753
hd_lv: 112.2854

patient008_frame13.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0027
Dice_lv: 0.0000
hd_rv: 62.0322
hd_myo: 74.6753
hd_lv: 112.2854

patient009_frame01.nii.gz
hd_rv: 91.6510
hd_myo: 80.1857
hd_lv: 97.2528

patient009_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0273
Dice_lv: 0.0263
hd_rv: 91.6510
hd_myo: 80.1857
hd_lv: 97.2528

patient009_frame13.nii.gz
hd_rv: 68.1337
hd_myo: 76.5692
hd_lv: 100.3444

patient009_frame13.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0538
Dice_lv: 0.0401
hd_rv: 68.1337
hd_myo: 76.5692
hd_lv: 100.3444

patient012_frame01.nii.gz
hd_rv: 67.4722
hd_myo: 99.8677
hd_lv: 100.7720

patient012_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0052
Dice_lv: 0.0148
hd_rv: 67.4722
hd_myo: 99.8677
hd_lv: 100.7720

patient012_frame13.nii.gz
hd_rv: 61.6141
hd_myo: 102.4920
hd_lv: 101.1046

patient012_frame13.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0169
Dice_lv: 0.0550
hd_rv: 61.6141
hd_myo: 102.4920
hd_lv: 101.1046

patient014_frame01.nii.gz
hd_rv: 41.8999
hd_myo: 92.3797
hd_lv: 76.6825

patient014_frame01.nii.gz
Dice_rv: 0.0059
Dice_myo: 0.0189
Dice_lv: 0.0392
hd_rv: 41.8999
hd_myo: 92.3797
hd_lv: 76.6825

patient014_frame13.nii.gz
hd_rv: 37.2424
hd_myo: 93.0261
hd_lv: 82.4742

patient014_frame13.nii.gz
Dice_rv: 0.0073
Dice_myo: 0.0292
Dice_lv: 0.0201
hd_rv: 37.2424
hd_myo: 93.0261
hd_lv: 82.4742

patient017_frame01.nii.gz
hd_rv: 75.0626
hd_myo: 89.7352
hd_lv: 104.4079

patient017_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0029
Dice_lv: 0.0060
hd_rv: 75.0626
hd_myo: 89.7352
hd_lv: 104.4079

patient017_frame09.nii.gz
hd_rv: 73.0007
hd_myo: 93.9683
hd_lv: 108.6508

patient017_frame09.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0073
Dice_lv: 0.0022
hd_rv: 73.0007
hd_myo: 93.9683
hd_lv: 108.6508

patient024_frame01.nii.gz
hd_rv: 68.4792
hd_myo: 90.4135
hd_lv: 107.5407

patient024_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0514
Dice_lv: 0.0057
hd_rv: 68.4792
hd_myo: 90.4135
hd_lv: 107.5407

patient024_frame09.nii.gz
hd_rv: 33.6155
hd_myo: 95.4018
hd_lv: 113.2961

patient024_frame09.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0018
Dice_lv: 0.0135
hd_rv: 33.6155
hd_myo: 95.4018
hd_lv: 113.2961

patient042_frame01.nii.gz
hd_rv: 69.6419
hd_myo: 120.7951
hd_lv: 110.6097

patient042_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0000
Dice_lv: 0.0229
hd_rv: 69.6419
hd_myo: 120.7951
hd_lv: 110.6097

patient042_frame16.nii.gz
hd_rv: 57.1034
hd_myo: 120.7442
hd_lv: 114.2650

patient042_frame16.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0000
Dice_lv: 0.0531
hd_rv: 57.1034
hd_myo: 120.7442
hd_lv: 114.2650

patient048_frame01.nii.gz
hd_rv: 66.6059
hd_myo: 81.9582
hd_lv: 105.7329

patient048_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0003
Dice_lv: 0.0477
hd_rv: 66.6059
hd_myo: 81.9582
hd_lv: 105.7329

patient048_frame08.nii.gz
hd_rv: 65.4458
hd_myo: 83.0602
hd_lv: 112.8105

patient048_frame08.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0046
Dice_lv: 0.0126
hd_rv: 65.4458
hd_myo: 83.0602
hd_lv: 112.8105

patient049_frame01.nii.gz
hd_rv: 53.1644
hd_myo: 89.5637
hd_lv: 128.9333

patient049_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0430
Dice_lv: 0.0313
hd_rv: 53.1644
hd_myo: 89.5637
hd_lv: 128.9333

patient049_frame11.nii.gz
hd_rv: 101.0940
hd_myo: 92.1358
hd_lv: 131.3324

patient049_frame11.nii.gz
Dice_rv: 0.0013
Dice_myo: 0.0188
Dice_lv: 0.0380
hd_rv: 101.0940
hd_myo: 92.1358
hd_lv: 131.3324

patient053_frame01.nii.gz
hd_rv: 122.7467
hd_myo: 96.3878
hd_lv: 127.2360

patient053_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0728
Dice_lv: 0.0079
hd_rv: 122.7467
hd_myo: 96.3878
hd_lv: 127.2360

patient053_frame12.nii.gz
hd_rv: 122.7096
hd_myo: 98.8683
hd_lv: 133.4103

patient053_frame12.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0022
Dice_lv: 0.0090
hd_rv: 122.7096
hd_myo: 98.8683
hd_lv: 133.4103

patient055_frame01.nii.gz
hd_rv: 114.0702
hd_myo: 103.0825
hd_lv: 102.4353

patient055_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0032
Dice_lv: 0.0117
hd_rv: 114.0702
hd_myo: 103.0825
hd_lv: 102.4353

patient055_frame10.nii.gz
hd_rv: 47.6707
hd_myo: 107.0091
hd_lv: 105.7852

patient055_frame10.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0055
Dice_lv: 0.0000
hd_rv: 47.6707
hd_myo: 107.0091
hd_lv: 105.7852

patient064_frame01.nii.gz
hd_rv: 74.9667
hd_myo: 107.5156
hd_lv: 114.1464

patient064_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0124
Dice_lv: 0.0682
hd_rv: 74.9667
hd_myo: 107.5156
hd_lv: 114.1464

patient064_frame12.nii.gz
hd_rv: 68.7677
hd_myo: 109.0431
hd_lv: 117.1108

patient064_frame12.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0351
Dice_lv: 0.0673
hd_rv: 68.7677
hd_myo: 109.0431
hd_lv: 117.1108

patient067_frame01.nii.gz
hd_rv: 67.9412
hd_myo: 100.1714
hd_lv: 101.1200

patient067_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0353
Dice_lv: 0.1424
hd_rv: 67.9412
hd_myo: 100.1714
hd_lv: 101.1200

patient067_frame10.nii.gz
hd_rv: 67.9412
hd_myo: 103.9519
hd_lv: 99.0656

patient067_frame10.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0799
Dice_lv: 0.1669
hd_rv: 67.9412
hd_myo: 103.9519
hd_lv: 99.0656

patient079_frame01.nii.gz
hd_rv: 80.4301
hd_myo: 121.6643
hd_lv: 112.8273

patient079_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0378
Dice_lv: 0.0234
hd_rv: 80.4301
hd_myo: 121.6643
hd_lv: 112.8273

patient079_frame11.nii.gz
hd_rv: 51.3936
hd_myo: 127.2053
hd_lv: 123.0197

patient079_frame11.nii.gz
Dice_rv: 0.0006
Dice_myo: 0.0086
Dice_lv: 0.0444
hd_rv: 51.3936
hd_myo: 127.2053
hd_lv: 123.0197

patient081_frame01.nii.gz
hd_rv: 71.5612
hd_myo: 95.4125
hd_lv: 99.2824

patient081_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0041
Dice_lv: 0.0053
hd_rv: 71.5612
hd_myo: 95.4125
hd_lv: 99.2824

patient081_frame07.nii.gz
hd_rv: 51.4451
hd_myo: 97.0000
hd_lv: 103.8220

patient081_frame07.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0085
Dice_lv: 0.0018
hd_rv: 51.4451
hd_myo: 97.0000
hd_lv: 103.8220

patient088_frame01.nii.gz
hd_rv: 60.8169
hd_myo: 99.6218
hd_lv: 93.9191

patient088_frame01.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0000
Dice_lv: 0.0135
hd_rv: 60.8169
hd_myo: 99.6218
hd_lv: 93.9191

patient088_frame12.nii.gz
hd_rv: 27.4773
hd_myo: 100.9121
hd_lv: 100.0620

patient088_frame12.nii.gz
Dice_rv: 0.0000
Dice_myo: 0.0000
Dice_lv: 0.0031
hd_rv: 27.4773
hd_myo: 100.9121
hd_lv: 100.0620

patient092_frame01.nii.gz
hd_rv: 19.0526
hd_myo: 78.1521
hd_lv: 103.9016

patient092_frame01.nii.gz
Dice_rv: 0.0077
Dice_myo: 0.0209
Dice_lv: 0.0439
hd_rv: 19.0526
hd_myo: 78.1521
hd_lv: 103.9016

patient092_frame06.nii.gz
hd_rv: 21.5430
hd_myo: 76.9571
hd_lv: 107.2476

patient092_frame06.nii.gz
Dice_rv: 0.0250
Dice_myo: 0.1117
Dice_lv: 0.0654
hd_rv: 21.5430
hd_myo: 76.9571
hd_lv: 107.2476

patient095_frame01.nii.gz
hd_rv: 23.3463
hd_myo: 36.8170
hd_lv: 106.4070

patient095_frame01.nii.gz
Dice_rv: 0.0039
Dice_myo: 0.0014
Dice_lv: 0.0530
hd_rv: 23.3463
hd_myo: 36.8170
hd_lv: 106.4070

patient095_frame12.nii.gz
hd_rv: 30.2655
hd_myo: 29.3019
hd_lv: 112.3871

patient095_frame12.nii.gz
Dice_rv: 0.0076
Dice_myo: 0.2153
Dice_lv: 0.1232
hd_rv: 30.2655
hd_myo: 29.3019
hd_lv: 112.3871

Mean_Dice
Dice_rv0.0014833411610974427
Dice_myo0.025901555917205978
Dice_lv0.036925817218667785
Mean_HD
HD_rv68.9724658656119
HD_myo94.56059658967824
HD_lv107.05783058276431

avg_hd:90.19696434601815
DSC:0.02143690476565707
HD:90.19696434601815

**Comment by Amshaker** [comment]
I am not sure what is the problem in your code. You can simply report the results you got in the validation set results of summary.json in the validation_raw_postprocessed folder. Both are correct.
