### ISSUE TITLE
Problem about the unetr baseline

### ISSUE THREAD

**Issue by Jason7282** [Amshaker/unetr_plus_plus#6]
Dear authors, thanks for your impressive work. 

I am curious about the baseline results of unetr, did you also run this baseline model based on your project? I found that you are based on the nnunet project. Did the impressive improvement due to the preprocessing of the training data as the nnunet project? As the improvement of Dice is not so obvious compared with the nnunet baseline.

**Comment by Amshaker** [comment]
Hi @Jason7282 

Thank you for your interesting question.

The DSC of the baseline UNETR we reported on the Synapse dataset (78.35%) is based on our codebase (built over nnunet project). So the comparison of DSC (87.22% vs 78.35%) is based on the exact preprocessing (based on nnunet project) and the same input sizes of 128x128x64.

I hope it is clear now. Please let me know if you have any questions.

Best regards,
Abdelrahman.
