### ISSUE TITLE
About the final comparison results

### ISSUE THREAD

**Issue by lijincan11** [Amshaker/unetr_plus_plus#61]
Disturbed the author! I have a question. Do all results need to be passed through the test set first, averaged across all organs, and then post-processed? I mean get the summary.json in the validation_raw_postprocessed file first and then post-process it? And the final results are all post-processed? Don't know if my understanding is correct

**Comment by Amshaker** [comment]
Hi @lijincan11 ,

The results inside summary.json within validation_raw_postprocessed folder are already post-processed. No more post-processing is needed. This is the final comparison results.
